ifeq ($(MODNAME),)
	KERNEL_BUILD := 1
else
	KERNEL_BUILD := 0
endif

ifeq ($(KERNEL_BUILD), 1)
	AUDIO_BLD_DIR := $(shell pwd)/kernel/msm-5.4
	AUDIO_ROOT := $(AUDIO_BLD_DIR)/techpack/audio
endif

ifeq ($(KERNEL_BUILD), 0)
	ifeq ($(CONFIG_ARCH_LAHAINA), y)
		include $(AUDIO_ROOT)/config/lahainaauto.conf
		export
		INCS    +=  -include $(AUDIO_ROOT)/config/lahainaautoconf.h
	endif
	ifeq ($(CONFIG_MACH_XIAOMI_REDWOOD), y)
		include $(AUDIO_ROOT)/config/redwoodaudio.conf
		export
		INCS    +=  -include $(AUDIO_ROOT)/config/redwoodaudioconf.h
	endif
	ifeq ($(CONFIG_MACH_XIAOMI_LISA), y)
		include $(AUDIO_ROOT)/config/lisaaudio.conf
		export
		INCS    +=  -include $(AUDIO_ROOT)/config/lisaaudioconf.h
	endif
endif

# for miui sensorhal
ifdef CONFIG_MIUS_IIO
	MIUS_IIO_OBJS += us_prox.o
	MIUS_IIO_OBJS += kefifo_buf.o
endif

INCS += $(AUDIO_BLD_DIR)/drivers/iio

obj-$(CONFIG_MIUS_IIO) += us_prox_iio.o
us_prox_iio-y := $(MIUS_IIO_OBJS)
