#define CONFIG_SND_SOC_TFA98XX 1
#define CONFIG_MACH_XIAOMI 1
#define CONFIG_SOFT_PCM_DISABLE 1
#define CONFIG_TARGET_PRODUCT_LISA 1
#define CONFIG_MIUS_IIO 1
#define CONFIG_MIUS_PROXIMITY 1
#define CONFIG_XIAOMI_US_PROX 1
